app/urls.py
from django.urls import path
from app import views

urlpatterns = [
    path("echo/", views.echo_page),
    path("liveblog/", views.liveblog_index),
    path("liveblog/posts/<int:post_id>/", views.post_partial, name="post_partial")
]

chat/urls.py
from django.urls import path, include
from chat import views

app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.room_new, name="room_new"),
    path("<str:room_name>/chat/", views.room_chat, name="room_chat"),
    path("<str:room_name>/chat/")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('chat/', include('chat.urls')),
    path('', RedirectView.as_view(pattern_name="chat:index"), name="root")
]

app/models.py
from django.db import models
from app.mixins import ChannelLayerGroupSendMixin
from django.db.models.signals import post_save, post_delete
from django.urls import reverse

# Create your models here.
class Post(ChannelLayerGroupSendMixin, models.Model):
    CHANNEL_LAYER_GROUP_NAME = 'liveblog'

    title = models.CharField(max_length=100)
    content = models.TextField()

    class Meta:
        ordering = ["-id"] # 쿼리셋의 디폴트 정렬

def post__on_post_save(instance: Post, created: bool, **kwras):
    if created:
        message_type ="liveblog.post.created"
    else:
        message_type = "liveblog.post.updated"

    post_id = instance.pk 
    post_partial_url = reverse("post_partial", args=[post_id])

    instance.channel_layer_group_send({
       "type": message_type,
       "post_id": post_id,
       "post_partial_url": post_partial_url 
    })

def post__on_post_delete(instance: Post, **kwargs):
    post_id = instance.pk 

    instance.channel_layer_group_send({
        "type": "liveblog.post.deleted",
        "post_id": post_id
    })

post_save.connect(
    post__on_post_save,
    sender=Post,
    dispatch_uid="post__on_post_save"
)

post_delete.connect(
    post__on_post_delete,
    sender=Post,
    dispatch_uid="post__on_post_delete"
)

chat/models.py
from django.db import models

# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=100)

    @property
    def chat_group_name(self):
        return self.make_chat_group_name(room=self)

    @staticmethod
    def make_chat_group_name(room=None, room_pk=None):
        return "caht-%s" % (room_pk or room.pk)

app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

# Create your views here.
def echo_page(request):
    return render(request, "app/echo_page.html")

def liveblog_index(request):
    post_qs = Post.objects.all()
    return render(request, "app/liveblog_index.html", {
        "post_list": post_qs,
    });

def post_partial(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, "app/partial/post.html", {
        "post": post
    });

chat/views.py
from django.shortcuts import render

from chat.forms import RoomForm

# Create your views here.
def index(request):
    return render(request, "chat/index.html")

def room_chat(request, room_pk):
    room = get_object_or_404(Room, pk=room_pk)
    return render(request, "chat/room_chat.html", {
        "room_name": room,
    })

def room_new(request):
    if request.method == "POST":
        form = RoomForm(request.POST)
        if form.is_valid():
            created_room = form.save()
            return redirect("chat:room_chat", created_room.pk)
    else:
        rom = RoomForm()

    return render(request, "chat/room_form.html", {
        "form": form
    })

app/templates/app/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liveblog by django channels</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <h1>LiveBlog</h1>
    {% block content %} {%endblock%}

    {% block extra-body %}
        <script>
            const handlers = {
                ws: null,
                connect(ws_url){
                    this.ws = new WebSocket(ws_url);

                    this.ws.open = this.onopen.bind(this);
                    this.ws.onclose = this.onclose.bind(this);
                    this.ws.onerror = this.onerror.bind(this);
                    this.ws.onmessage = this.onmessage.bind(this);
                },
                onopen(){
                    console.log("웹소켓 서버와 접속")
                },
                onclose(event){
                    if(!event.wasClean){
                        console.error("웹소켓 서버가 죽거나 네트워크 장애입니다.");
                    }
                },
                onerror(){
                    console.error("웹소켓 에러가 발생했습니다.");
                },
                onmessage(event) {
                    const message_json = event.data;
                    console.log("웹소켓 텍스트 메세지 수신 : ", message_json);

                    const { type, post_id, post_partial_url } = JSON.parse(message_json); 

                    switch(type){
                        case "liveblog.post.created":
                            this.post_created(post_id, post_partial_url);
                            break;
                        case "liveblog.post.updated":
                            this.post_updated(post_id, post_partial_url);
                            break;
                        case "liveblog.post.deleted":
                            this.post_deleted(post_id);
                            break;
                        default:
                            console.error('INvaild message type : $(type)');
                    }
                },
                post_created(post_id, post_partial_url){
                    fetch(post_partial_url) // 지정 주수로 http get 요청을 보내는 함수
                        .then(response => response.text())
                        .then(html => {
                            console.log('html', html);

                            // 임시 요소 생성
                            var tempDiv = document.createElement('div');
                            tempDiv.innerHTML = html;

                            // 임시 요소의 첫 번째 자식 요소를 실제로 사용하려는 요소
                            var newElement = tempDiv.firstChild;

                            document.querySelector("#post-list")
                                .insertAdjacentElement("afterbegin", newElement);
                        })
                },
                post_updated(post_id, post_partial_url){
                    fetch(post_partial_url)
                        .then(response => respones.text())
                        .then(html => {
                            const css_selector = '[data-post-id="' + post_id  + '"]';
                            document.querySelector(css_selector).outerHTML = html;
                        });
                },
                post_deleted(post_id){
                    const css_selector = '[data-post-id="' + post_id  + '"]';
                    document.querySelector(css_selector).remove();
                }              
            };

        const ws_url = "ws://localhost:8000/ws/liveblog/";
        handlers.connect(ws_url);
        </script>
    {% endblock %}
</body>
</html>

app/templates/app/echo_page.html
<!DOCTYPE html>
<html>
  <head>
    <title>웹소켓 Echo</title>
  </head>
  <body>
    웹소켓 Echo ...

    <script>
        const ws = new WebSocket("ws://localhost:8000/ws/echo/");

        ws.onopen = () => {
            console.log("웹소켓 서버와 접속됨.");            
        };

        ws.onmessage = (event) => {
            const json_string = event.data;
            const obj = JSON.parse(json_string);
            console.log("메세지 수신 :", obj);
        };

        ws.onerror = () => {
            console.error("웹소켓 에러 발생")
        };

        ws.onclose = (event) => {
            if (event.wasClean){
                console.log("ws.close()에 의한 연결 끊기")
            }else{
                console.log("웹소켓 서버와의 네트워크 단절로 인한 끊김")
            }
        };
    </script>
  </body>
</html>

app/templates/app/liveblog_index.html
{% extends "app/base.html" %}

{% block content %}
    <div class="conteiner">
        <h1>Hello</h1>
        
        <div class="row" id="post-list">
            {% for post in post_list %}
                {% include "app/partial/post.html" with post=post only%}
            {% endfor %}
        </div>
    </div>
{% endblock%}

app/templates/app/partial/post.html
<div class="col-sm-4" data-post-id="{{ post.id }}">
    <div class="card">
        <img src="https://via.placeholder.com/572x360.png"
             alt="placeholder image"
             class="card-img-top" />
        <div class="card-body">
            <h5 class="card-title">
                #{{ post.id }}. {{post.title}}
            </h5>
            <div class="card-text">
                {{ post.content|truncatewords:10 }}
            </div>
        </div>
    </div>
</div>

chat/templates/chat/base.html
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Channels</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% block extra-style %}{% endblock %}
</head>
<body>
    {% bootstrap_messages %}
    {% block content %}{% endblock %}
    {% block extra-script %}{% endblock %}
</body>
</html>

chat/templates/chat/index.html
{% extends "chat/base.html" %}

{% block content %}
    <h1>채팅방 목록</h1>
    <ul>
        <li>
            <!--TODO: 채팅방 목록을 조회하여 렌더링하기-->
            <a href="{% url 'chat:room_chat' 'test' %}">테스트 채팅방 진입</a>
        </li>
    </ul>

    <a href="{% url 'chat:room_new'%}">
        새 채팅방 만들기
    </a>
{% endblock %}

chat/templates/chat/room_chat.html
{% extends "chat/base.html" %}

{% block extra-style %}
<style>
    .chat-message > div{
        background-color: #3b3b3b;
        color: #e1e1e1;
        border-radius: 0.8em;
        padding: 0.4em;
        margin: 0.4em 0;
        display: inline-block;
        white-space: pre-wrap;
        max-width: 80%;
        word-wrap: break-word;
    }
</style>
{% endblock %}

{% block content %}
    <div class="container my-5">
        <div class="row">
            <div class="col-sm-12">
                <div class="card" style="height: 600px;">
                    <div class="card-header">
                        채팅방: {{room.name}}
                    </div>
                    <div class="card-body overflow-hidden">
                        <div id="chat_messages" class="w-100 h-100 border-0 overflow-scroll"></div>
                    </div>
                    <div class="card-footer">
                        <form id="message_form">
                            <input type="text" name="message" class="form-control" autofocus autocomplete="off" />
                        </form>
                    </div>
                </div>

                <hr class="my-3">
                
                <a href="{% url 'chat:index' %}" class="btn btn-primary">대기실로 이동</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra-script %}
<script>
    const handlers = {
        chat_message_tag: null,
        ws: null,
        retry: 0,
        init(){
            this.chat_message_tag = document.querySelector("#chat_messages");
            document.querySelector("#message_form")
                .addEventListener("submit", this.onsubmit.bind(this));
        },
        connect(ws_url){
            if (this.ws){
                this.ws.close();
            } 
            console.log(ws_url);
            this.ws = new WebSocket(ws_url);

            this.ws.onopen = this.onopen.bind(this);
            this.ws.onclose = this.onclose.bind(this);
            this.ws.onerror = this.onerror.bind(this);
            this.ws.onmessage = this.onmessage.bind(this);
        },
        reconnect(){
            this.connect();
        },
        onopen(){
            console.log("웹소켓 서버와 접속");
            this.retry = 0;
        },
        onclose(event){
            if (!event.wasClean){
                console.error("웹소켓 서버가 죽었거나, 네트워크 장애입니다.");
                if (this.retry < 3){
                    this.retry += 1;
                    setTimeout(() => {
                        this.reconnect();
                        console.log('[' + this.retry + ']' + '접속 재시도 ...')
                    }, 1000 * this.retry);
                }else{
                    console.log("웹소켓 서버에 접속할 수 없습니다. 대기실로 이동합니다.");
                    window.location.href = "{% url 'chat:index' %}";
                }
            }
        },
        onerror(){
            console.log("웹소켓 에러가 발생했습니다. 대기실로 이동합니다.");
            window.location.href ="{% url 'chat:index' %}"
        },
        onmessage(event){
            const message_json = event.data;
            console.log("메세지 수신 : ", message_json);
            const {type, message} = JSON.parse(message_json);
            switch(type){
                case "chat.message":
                    this.append_message(message);
                    break;
                default:
                    console.error('Invalid message type : ' + type);

            }
        },
        append_message(message) {
            const element = document.createElement("div");
            element.className = "chat-message";

            const wrapper = document.createElement("div");
            wrapper.textContent = message;
            element.appendChild(wrapper);

            this.chat_message_tag.appendChild(element);
            this.chat_message_tag.scrollTop = this.chat_message_tag.scrollHeight;
        },
        onsubmit(evnet){
            event.preventDefault();
            
            const form_data = new FormData(event.target);
            const props = Object.fromEntries(form_data);
            event.target.reset();

            const { message } = props;
            console.log("웹소켓으로 전송할 메세지 : " + message);

            // this.append_message(message);
            this.ws.send(JSON.stringify({
                type: "chat.message", 
                message: message,
            }))
        }

    }

    const protocol = location.protocol === "http:" ? "ws:" : "wss:";
    const ws_url = protocol + "//" + location.host + "/ws" + location.pathname;

    handlers.connect(ws_url);
    handlers.init();
    console.log('ws_url', ws_url);
</script>
{% endblock %}

chat/templates/chat/room_form.html
{% extends "chat/base.html" %}
{% load django_bootstarp5%}

{% block content %}
    <h2>새 채팅방 만들기</h2>

    <div class="my-3">
        <form action="" method="post">
            {% csrf_token %}
            {%bootstrap_form form%}
            <input type="submit" value="만들기" class="btn btn-parimary" />
        </form>

        <a href="{% url 'chat:index' %}" class="btn btn-primary">대기실로 이동</a>
    </div>